Foundation3MVC4/Controllers/FoundationController.cs
using Foundation3MVC4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Foundation3MVC4.Controllers
{
  public class FoundationController : Controller
  {
    public ActionResult Index()
    {
      ViewBag.Message = "Welcome to ASP.NET MVC with Foundation 3.0.9!";

      return View();
    }

    public ActionResult Form()
    {
        var basicForm = new BasicFormModel();
        var items = new List<string>();
        items.Add("Option A");
        items.Add("Option B");
        items.Add("Option C");
        items.Add("Option D");

        basicForm.DropDownItems = new SelectList(items);

        return View(basicForm);
    }

  [HttpPost]
    public ActionResult Form(BasicFormModel basicForm)
    {
        var items = new List<string>();
        items.Add("Option A");
        items.Add("Option B");
        items.Add("Option C");
        items.Add("Option D");

        basicForm.DropDownItems = new SelectList(items);
        
        return View(basicForm);
    }

  }
}

Foundation3MVC4/Views/Foundation/Form.cshtml
@model Foundation3MVC4.Models.BasicFormModel

@{
    ViewBag.Title = "Form";
}

<div class="row">
    <div class="twelve columns">
        <h2>Form</h2>

        @using (Html.BeginForm("Form", "Foundation", FormMethod.Post, new { @class="custom" }))
        {
            @Html.ValidationSummary(true)

            <fieldset>
                <legend>BasicFormModel</legend>

                <div class="editor-label">
                    @Html.LabelFor(model => model.SampleField)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.SampleField)
                    @Html.ValidationMessageFor(model => model.SampleField)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Selected)
                </div>
                <div class="editor-field">
                    @Html.DropDownListFor(m => m.Selected, Model.DropDownItems, "choose....", null)
                    @Html.ValidationMessageFor(model => model.Selected)
                </div>
                

                <p>
                    <input type="submit" value="Create" />
                </p>
            </fieldset>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script> $("#customDropdown").foundationCustomForms();</script>
}

Foundation3MVC4/Views/Foundation/Index.cshtml
<div class="row">
    <div class="twelve columns">
        <h2>Welcome to Foundation</h2>
        <p>This is version <strong>3.2.5</strong> generated on January 26, 2013.</p>
        <hr />
    </div>
</div>

<div class="row">
    <div class="eight columns">
        <h3>The Grid</h3>

        <!-- Grid Example -->
        <div class="row">
            <div class="twelve columns">
                <div class="panel">
                    <p>This is a twelve column section in a row. Each of these includes a div.panel element so you can see where the columns are - it's not required at all for the grid.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="six columns">
                <div class="panel">
                    <p>Six columns</p>
                </div>
            </div>
            <div class="six columns">
                <div class="panel">
                    <p>Six columns</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="four columns">
                <div class="panel">
                    <p>Four columns</p>
                </div>
            </div>
            <div class="four columns">
                <div class="panel">
                    <p>Four columns</p>
                </div>
            </div>
            <div class="four columns">
                <div class="panel">
                    <p>Four columns</p>
                </div>
            </div>
        </div>


        <h3>Tabs</h3>
        <dl class="tabs">
            <dd class="active"><a href="#simple1">Simple Tab 1</a></dd>
            <dd><a href="#simple2">Simple Tab 2</a></dd>
            <dd><a href="#simple3">Simple Tab 3</a></dd>
        </dl>

        <ul class="tabs-content">
            <li class="active" id="simple1Tab">This is simple tab 1's content. Pretty neat, huh?</li>
            <li id="simple2Tab">This is simple tab 2's content. Now you see it!</li>
            <li id="simple3Tab">This is simple tab 3's content. It's, you know...okay.</li>
        </ul>



        <h3>Buttons</h3>

        <div class="row">
            <div class="six columns">
                <p><a href="#" class="small button">Small Button</a></p>
                <p><a href="#" class="button">Medium Button</a></p>
                <p><a href="#" class="large button">Large Button</a></p>
            </div>
            <div class="six columns">
                <p><a href="#" class="small alert button">Small Alert Button</a></p>
                <p><a href="#" class="success button">Medium Success Button</a></p>
                <p><a href="#" class="large secondary button">Large Secondary Button</a></p>
            </div>
        </div>

    </div>

    <div class="four columns">
        <h4>Getting Started</h4>
        <p>We're stoked you want to try Foundation! To get going, this file (index.cshtml) includes some basic styles you can modify, play around with, or totally destroy to get going.</p>

        <h4>Other Resources</h4>
        <p>Once you've exhausted the fun in this document, you should check out:</p>
        <ul class="disc">
            <li><a href="http://foundation.zurb.com/docs">Foundation Documentation</a><br />
                Everything you need to know about using the framework.</li>
            <li><a href="http://github.com/zurb/foundation">Foundation on Github</a><br />
                Latest code, issue reports, feature requests and more.</li>
            <li><a href="http://twitter.com/foundationzurb">@@foundationzurb</a><br />
                Ping us on Twitter if you have questions. If you build something with this we'd love to see it (and send you a totally boss sticker).</li>
        </ul>
    </div>
</div>


<div class="row">
    <div class="twelve columns">
        <h3>Orbit</h3>
        <div id="featured">
            <img src="http://placehold.it/1200x250&text=Slide_1" alt="slide image">
            <img src="http://placehold.it/1200x250&text=Slide_2" alt="slide image">
            <img src="http://placehold.it/1200x250&text=Slide_3" alt="slide image">
        </div>
    </div>
</div>



<div class="row">
    <div class="twelve columns">
        <h3>Reveal</h3>
        <p><a href="#" data-reveal-id="exampleModal" class="button">Example modal</a></p>
    </div>
</div>

<div id="exampleModal" class="reveal-modal">
    <h2>This is a modal.</h2>
    <p>
        Reveal makes these very easy to summon and dismiss. The close button is simple an anchor with a unicode 
      character icon and a class of <code>close-reveal-modal</code>. Clicking anywhere outside the modal will 
      also dismiss it.
   
    </p>
    <a class="close-reveal-modal">×</a>
</div>
@section scripts
{
    <script>
        $(window).load(function () {
            $("#featured").orbit();
        });
    </script>
}